name:                ScripScrap
version:             0.1.0.0
github:              "github.com/randomthought/ScripScrap"
license:             BSD3
author:              "Malcolm Mulong"
maintainer:          "example@example.com"
copyright:           "2019 Author Malcolm Mulong"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/randomthought/ScripScrap/blob/master/README.md>

dependencies:
- base >= 4.7 && < 5
- stm
- containers
- bytestring
- string-class
- tagsoup
- monad-loops
- curl == 1.3.8
- text
- hxt
- hxt-css
- hxt-curl
- HandsomeSoup
- optparse-applicative
# - pretty-simple
- mtl
# - bloomfilter
- lens
- yaml
- aeson
- transformers-base
- unliftio
- unliftio-core
- monad-control
- easy-file
- regex-tdfa
- tld
- wreq
- hashable

library:
  source-dirs: src

executables:
  ScripScrap-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ScripScrap

tests:
  ScripScrap-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ScripScrap
